microserviceName : "identity"

image: 
  repository: harvesthelper.azurecr.io/harvesthelper.identity
  tag: 1.0.37

envVariables:
   IdentitySettings__PathBase: /identity-svc
   IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
   IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"
   IdentityServerSettings__Clients__0__RedirectUris__0: "https://harvesthelper.westeurope.cloudapp.azure.com/authentication/login-callback"
   IdentityServerSettings__Clients__0__PostLogoutRedirectUris__0: "https://harvesthelper.westeurope.cloudapp.azure.com/authentication/logout-callback"

resources:
  limits:
    memory: "256Mi"
    cpu: "300m"

container:
  port: 5002 
  volumeMounts:
  - name: certificate-volume
    mountPath: /certificates

volumes: 
  - name: certificate-volume
    secret: 
      secretName: signing-cert
      items: 
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

certificate:
  secretName: signing-cert
  hostname: harvesthelper.westeurope.cloudapp.azure.com

identityClientId: 37b99f37-5379-446c-b8a4-a7d5ce4eb9cc