# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CIDC

on:
  push:
    branches: [ "main" ]

jobs:

  generate-version:
    runs-on: ubuntu-latest
  
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3   
    
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.65.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        INITIAL_VERSION: 1.0.12
        DEFAULT_BUMP: patch
        
    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}

  build-and-deploy-service:

    runs-on: ubuntu-latest
    needs: generate-version

    env:
      APP_NAME: harvesthelper
      
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        # ClientId of the Azure Service principal created.
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        # TenantId of the Azure Service principal created.
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        # Azure subscriptionId
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        
    - name: Login to container registry
      run: az acr login --name ${{env.APP_NAME}}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        secrets: |
          "GH_OWNER=${{github.repository_owner}}"
          "GH_PAT= ${{secrets.GH_PAT}}"
        tags: ${{env.APP_NAME}}.azurecr.io/harvesthelper.identity:${{ needs.generate-version.outputs.new_version }}
        push: true
